# Generated by Django 3.0.5 on 2020-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='acc_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='bank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
