# Generated by Django 3.0.5 on 2020-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subtitle',
            field=models.CharField(default='Small subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
