# Generated by Django 3.0.5 on 2020-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_cart_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantitiy',
            field=models.IntegerField(default=1),
        ),
    ]
