# Generated by Django 3.0.5 on 2020-04-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_cartitem_quantitiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantitiy',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
