# Generated by Django 3.0.5 on 2020-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20200416_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
